# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10
stages:
  - build
#  - test
  - docker
  - deploy

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm install
    - npm run build

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  cache: {}
  script:
    - docker login -u ${DEV_REGISTRY_USER} -p ${DEV_REGISTRY_PASS} ${DEV_REGISTRY_URL}
    - docker build -t ${DEV_REGISTRY_URL}/${DEV_IMAGE} .
    - docker push ${DEV_REGISTRY_URL}/${DEV_IMAGE}

app-deploy:
  stage: deploy
  image: heunghingwan/rancher-cli-k8s
  variables:
    GIT_STRATEGY: none
  cache: {}
  dependencies: []
  script:
    - rancher login ${RANCHER_URL} -t ${RANCHER_TOKEN} --context ${RANCHER_PROJECT_ID}
    - rancher kubectl --namespace="${DEV_STACK}" patch deployment "${DEV_SERVICE}" --type=strategic -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"${DEV_SERVICE}"'","image":"'"${DEV_REGISTRY_URL}"'/'"${DEV_IMAGE}"'","env":[{"name":"FORCE_RESTART_AT","value":"'"${CI_PIPELINE_ID}"'"}]}]}}}}'
