image: node:10
stages:
  - build
  - docker
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

app-build:
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm install
    - npm run build

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  cache: {}
  only:
    - master
  script:
    - docker login -u ${DEV_REGISTRY_USER} -p ${DEV_REGISTRY_PASS} ${DEV_REGISTRY_URL}
    - docker build -t ${DEV_REGISTRY_URL}/${DEV_IMAGE} .
    - docker push ${DEV_REGISTRY_URL}/${DEV_IMAGE}

docker-prd:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  cache: {}
  only:
    - prd
  script:
    - docker login -u ${PRD_REGISTRY_USER} -p ${PRD_REGISTRY_PASS} ${PRD_REGISTRY_URL}
    - docker build -t ${PRD_REGISTRY_URL}/${PRD_IMAGE} .
    - docker push ${PRD_REGISTRY_URL}/${PRD_IMAGE}

app-deploy:
  stage: deploy
  image: heunghingwan/rancher-cli-k8s
  variables:
    GIT_STRATEGY: none
  cache: {}
  dependencies: []
  only:
    - master
  script:
    - rancher login ${RANCHER_URL} -t ${RANCHER_TOKEN} --context ${RANCHER_PROJECT_ID}
    - rancher kubectl --namespace="${DEV_STACK}" patch deployment "${DEV_SERVICE}" --type=strategic -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"${DEV_SERVICE}"'","image":"'"${DEV_REGISTRY_URL}"'/'"${DEV_IMAGE}"'","env":[{"name":"FORCE_RESTART_AT","value":"'"${CI_PIPELINE_ID}"'"}]}]}}}}'

app-deploy-prd:
  stage: deploy
  image: heunghingwan/rancher-cli-k8s
  variables:
    GIT_STRATEGY: none
  cache: {}
  dependencies: []
  only:
    - prd
  script:
    - rancher login ${PRD_RANCHER_URL} -t ${PRD_RANCHER_TOKEN} --context ${PRD_RANCHER_PROJECT_ID}
    - rancher kubectl --namespace="${PRD_STACK}" patch deployment "${PRD_SERVICE}" --type=strategic -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"${PRD_SERVICE}"'","image":"'"${PRD_REGISTRY_URL}"'/'"${PRD_IMAGE}"'","env":[{"name":"FORCE_RESTART_AT","value":"'"${CI_PIPELINE_ID}"'"}]}]}}}}'
